# Site settings
title: Alessia
SEOTitle: Alessia XY Tang | Alessia
header-img: img/home-bg.jpg
email: huxpro@gmail.com
description: "techsavy"
keyword: "黄玄, Hux黄玄, Hux, 鬼栈, huxpro, @huxpro, 黄玄的博客, Hux Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://huangxuan.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: huxpro
zhihu_username: huxpro
github_username: huxpro
twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "techsavy"
sidebar-avatar: "https://lh3.googleusercontent.com/rd-gg-dl/ABS2GSmH6kjDkUimeMu4aYlKi1S51_sJzPo5vFRJjfEvoRIXWWLPF5bPQV_7Xjmt2hfyuafDEbwuyZ0MnMj1yYstqt8pdVWGB8RHRSWnKJB84kyqeSK-jejzNG1ITTI_HlkfuFmbjS71BNncBTXwOoyPOHbFqKyFXZcQeprj5xRP7irE6g3uM0nLhYiyfTkbPImpWBDg4aSbqjZHEcST-za4X7YA9afvBzMtTc_IlMATy_U9XRThpk3zl8nNlLeU8E7SYm8sDKEUxVe-cVH6pmKejYWeqoZ_dOo6q8E9AsgtZYPeVlzBCOEirW051J99StJWwLn4yeUF8AX6g_tcuqNntfZQ00TCQpr6BjEPrkeSqkt9KmcalFHN3ndxJ-SPWwqco7ExPvDmoq1DFX1CG4saRePt88skj72UDCU0AVG52Rebcdy5OA0CLC4Mq4ofHDOu1UhymK5lBIWHI6a3CCkz1xi9dNMFMMEhNVKjBmMU6P0LhNRR--GjuLvlISCFl8m122YSE_-SW2k0GDYNBwphlBJ4_5HRJ2Y7rqkTkvwBpA8sjGTcICXk0B_Or8zJBSrC6hpB9eE00Gps6Mo_OzrOzNXmHuLcK6iLfLR3_mrAArfxTKuFJUDM_zStHJ5v49I-8NwH504hzk4ZllnK2JapRapnPKxdmF0qGpnOBftLxAbQntz0TWCTLVu41ZIoewv6S1rWnJYExiPcJKArmBGUpem6JNc6tEwiVgezEoPIBA3YiW_xPrP1qdI-fZmhG1mrhnXWp6Nj_uV-oeMjrTzcTLcQRQ9EbSftmoIHqXN37KMKTUy-IHtYUL62woZTVdZv0C6BS_8xGskOuOlH5VvRHm5Ci8Un45A0Kv_nY8wZA58H1yY4Qzy7ACpUH984pZwJgOcnANyNyuSUgHnwgEO4V03qp7gEdVXd1D5v55E_XN_npUD-aSuPvOWFhk5EjzyeCyT5I42C9qQTTyw3ai49KZFu6Is219TuYikxDI4Id76k8sRCDVLiLW8AQw4StOek4zbVDa0v-X_lAmDAq9T3_8LY3PygXM7kHHy5jBJkySMk13vlYBgS0mJ_xDbTMcwIdcl8Cj90bPFUOnRZt9-u3X11ijZEJB35LikgbXNJg-F5P-P67muzLHlJI86GpzmF6VraGx4oQi5cP3pmpw5GtnKT5vai5JE9X-BLfw5tlT7FU6tPQrMwiFw=s1024-rj"

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "乱序（Midare）", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "尹峰以为", href: "http://ingf.github.io/" },
  ]
